### PR TITLE
update README for node role, to include 'architecture' param

### PR DESCRIPTION
**Pull request by twrichards**
The architecture param was introduced in https://github.com/guardian/amigo/pull/533 but not documented, so adding it here for future travelers.

### CODE REVIEW

**Comment by twrichards** [comment]
FYI @rBangay

**Review by tomrf1 — APPROVED** [review]
👍

**Comment by Fweddi** [comment]
Guy and I encountered this scenario with another role, where we made the 'architecture' injection a case of automatic detection rather than a manual parameter (See https://github.com/guardian/amigo/pull/540/files, and https://docs.google.com/document/d/1J6zBuz9P5E57XFNKj2Pb75Z1AYDb01bzz6_FFKtQo50/edit#heading=h.ypqm5kuc0fv5 for more detail). Might be worth adding here?

**Comment by twrichards** [comment]
> Guy and I encountered this scenario with another role, where we made the 'architecture' injection a case of automatic detection rather than a manual parameter (See https://github.com/guardian/amigo/pull/540/files, and https://docs.google.com/document/d/1J6zBuz9P5E57XFNKj2Pb75Z1AYDb01bzz6_FFKtQo50/edit#heading=h.ypqm5kuc0fv5 for more detail). Might be worth adding here?

Excellent suggestion. Phil's original PR mentions that in fact #533 - I'm fairly rusty on ansible but I suspect we could leave this `architecture` param but update the default to be calculated from `ansible_architecture`, I'll take a punt at it later unless @philmcmahon beats me to it

**Pull request merged**
