### PR TITLE
Update aws-cloudwatch-agent role to support ARM64 architecture

### PR DESCRIPTION
**Pull request by Mullefa**
## What does this change?

\* worked on with @Fweddi 

Update the `aws-cloudwatch-agent` role to dynamically install the `amazon-cloudwatch-agent.deb` dynamically based on the architecture (architectures supported: amd64, arm64).

Uses the Ansible fact `ansible_architecture` to determine the architecture.

Tested on CODE by:
1. creating a new base image `ARM ubuntu-xenial` (as was done on PROD)
2. cloning the recipe `ubuntu-xenial-capi` (clone name: `ubuntu-xenial-capi-ARM`) and changing the base image to `ARM ubuntu-xenial`
3. baking recipes [`ubuntu-xenial-capi`](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi/bakes/2) and [`ubuntu-xenial-capi-ARM`](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi-ARM/bakes/1) and eyeballing the logs to check the appropriate package was installed

### CODE REVIEW

**Review by tonytw1 — APPROVED** [review]
This looks like a sensible approach and sensible switching on architecture.

The name of the cloudwatch recipe suggests it's a global used by all teams so fairly large impact. Slight risk of making ARM work and forgetting to regression test an x86 application which depends on cloudwatch.

**Comment by Mullefa** [comment]
Good point Tony. We are going to run Concierge CODE on a bake of the recipe `ubunut-xenial-capi`, with the updated role `aws-cloudwatch-agent` included.

Note that the use of the role is not as prevalent as you'd expect; other roles are also used to send metrics to Cloudwatch e.g. `cloudwatch-monitoring-hardware-cronjob`. The different roles are a result of AWS' advice changing over time.

**Review by JustinPinner — APPROVED** [review]
Looks sensible to me 👍

**Review by philmcmahon — APPROVED** [review]

**Comment by Mullefa** [comment]
> We are going to run Concierge CODE on a bake of the recipe ubunut-xenial-capi, with the updated role aws-cloudwatch-agent include [to check there are no errors]

Done ✅

**Pull request merged**
