### PR TITLE
install latest nvm from an up to date source

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?

It looks like nvm has moved into the [`nvm-sh` organisation](https://github.com/nvm-sh/nvm#installing-and-updating), so install it from there.

## How to test

- Deploy to CODE
- Build a TeamCity agent
- Witness it succeed

## How can we measure success?

Keeping up to date.

## Have we considered potential risks?

n/a

## Images

image

### CODE REVIEW

**Review by sihil — APPROVED** [review]
Nice find. LGTM.

**Comment by AWare** [comment]
I'm not 100% sure this is actually in use. The teamcity node plugin might supply it's own- but it's not clear. Otherwise, I think people should be using node from docker in teamcity.  


Buuut, unless we remove nvm completely, this is:+1:

**Comment by sihil** [comment]
I'm aware of a number of builds that use nvm inside a shell script. We should, and I'm aware I sound like a broken record, never use the custom build types in TeamCity. The only config in TeamCity should be pointing to a shell script - we should avoid encapsulating build ordering/logic outside of VCS.

**Comment by akash1810** [comment]
> I'm not 100% sure this is actually in use.

It looks like we're [using](https://teamcity.gutools.co.uk/admin/admin.html?item=plugins) a [TC Plugin](https://github.com/jonnyzzz/TeamCity.Node) rather than this part of the AMIgo role; this part of the role can be deleted. Not sure how the plugin gets added to the server however...

**Comment by sihil** [comment]
Is that true for both use of an nvm build step and also running nvm via a shell script?

The plugins are installed in the admin interface and persisted onto EFS where the main server files are stored.

**Review by jacobwinch — APPROVED** [review]

**Comment by akash1810** [comment]
This seems to be solving this problem on PROD:

```
[2022-05-03 13:41:43] teamcity-agent-focal: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "set -e
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source /opt/teamcity/.nvm/nvm.sh
nvm install node
nvm install --lts
", "delta": "0:00:05.507657", "end": "2022-05-03 14:41:43.236341", "msg": "non-zero return code", "rc": 11, "start": "2022-05-03 14:41:37.728684", "stderr": " % Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 12819 100 12819 0 0 81132 0 --:--:-- --:--:-- --:--:-- 81132
Cloning into '/opt/teamcity/.nvm'...
Downloading https://nodejs.org/dist/v18.1.0/node-v18.1.0-linux-x64.tar.xz...
########################################### 59.9% ######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
nvm is not compatible with the npm config \"prefix\" option: currently set to \"\"
Run `nvm use --delete-prefix v18.1.0` to unset it.", "stderr_lines": [" % Total % Received % Xferd Average Speed Time Time Time Current", " Dload Upload Total Spent Left Speed", "", " 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0", "100 12819 100 12819 0 0 81132 0 --:--:-- --:--:-- --:--:-- 81132", "Cloning into '/opt/teamcity/.nvm'...", "Downloading https://nodejs.org/dist/v18.1.0/node-v18.1.0-linux-x64.tar.xz...", "", "########################################### 59.9%", "######################################################################## 100.0%", "Computing checksum with sha256sum", "Checksums matched!", "node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)", "nvm is not compatible with the npm config \"prefix\" option: currently set to \"\"", "Run `nvm use --delete-prefix v18.1.0` to unset it."], "stdout": "=> Downloading nvm from git to '/opt/teamcity/.nvm'
=> => Compressing and cleaning up git repository

=> Appending nvm source string to /opt/teamcity/.bashrc
=> Appending bash_completion source string to /opt/teamcity/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR=\"$HOME/.nvm\"
[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\" # This loads nvm
[ -s \"$NVM_DIR/bash_completion\" ] && \\. \"$NVM_DIR/bash_completion\" # This loads nvm bash_completion
Downloading and installing node v18.1.0...", "stdout_lines": ["=> Downloading nvm from git to '/opt/teamcity/.nvm'", "", "=> => Compressing and cleaning up git repository", "", "=> Appending nvm source string to /opt/teamcity/.bashrc", "=> Appending bash_completion source string to /opt/teamcity/.bashrc", "=> Close and reopen your terminal to start using nvm or run the following to use it now:", "", "export NVM_DIR=\"$HOME/.nvm\"", "[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\" # This loads nvm", "[ -s \"$NVM_DIR/bash_completion\" ] && \\. \"$NVM_DIR/bash_completion\" # This loads nvm bash_completion", "Downloading and installing node v18.1.0..."]}
```

**Comment by akash1810** [comment]
This PR was originally intended to keep this up to date. It was _merged_ ~2 years later because we were seeing AMIgo bakes fail with errors about `GLIBC_2.28` missing.

During a bake, we perform [these steps](https://github.com/guardian/amigo/blob/64e57c2f9f03a82fe8f87f6d62575ab884f83b92/roles/teamcity-agent/tasks/main.yml#L66-L76):

```sh
source nvm.sh
nvm install node
nvm install --lts
```

The `nvm install node` command will (today) install Node 18, and Node 18 has a [new dependency on `GLIBC_2.28`](https://nodejs.org/en/blog/announcements/v18-release-announce/#toolchain-and-compiler-upgrades). That is, the build errors (when using nvm 0.33.11) _must_ have started since the release of Node 18. (A similar report is on the [CloudFlare forums](https://community.cloudflare.com/t/pages-build-failed-when-using-node-18-due-to-missing-glibc/379201)).

_Somehow_, updating to nvm 0.39.1 removes the `GLIBC_2.28` error and the bake succeeds.

OK, so the AMIgo bake succeeds, but we're seeing TeamCity builds failing with an exit code of 3. This is new, and possibly related to https://github.com/nvm-sh/nvm/issues/1985. Initial hypothesis is something has changed in the `nvm.sh` file which all projects source as their first steps (e.g [here](https://github.com/guardian/teamcity-nvm-debug/blob/1314f29a324e633b4def29ca7aff4e25eb3697c8/script/ci#L7)).

**Pull request merged**
