### PR TITLE
who wouldn't want a big ulimit?

### PR DESCRIPTION
**Pull request by johnduffell**
We are hitting ulimits on membership.  Since we are all running single purpose machines, I doubt everyone would complain about one user opening lots of files.  And the jvm does like to open lots of files...

@rtyley

### CODE REVIEW

**Comment by rtyley** [comment]
Here's an example of the exceptions we're getting - they say "Too many open files":

image

https://sentry.io/the-guardian/membership/issues/182649206/

**Comment by johnduffell** [comment]
@LATaylor-guardian will that cause any issue moving the ulimit for kong?

**Comment by LATaylor-guardian** [comment]
@johnduffell I don't believe so as the Kong image uses ubuntu-init as a base image so it should still pick this up.

**Comment by rtyley** [comment]
:+1: - the CI build seems to be using bad credentials for RiffRaff upload tho.

**Comment by johnduffell** [comment]
opened a new one from a branch instead of a fork https://github.com/guardian/amigo/issues/90

**Pull request closed without merging**
