### PR TITLE
Adds role to install pluto

### PR DESCRIPTION
**Pull request by kenoir**

### CODE REVIEW

**Comment by fredex42** [comment]
please keep me updated as progress on this as well, working with @kenoir

**Comment by LATaylor-guardian** [comment]
@kenoir build is failing.

**Comment by cb372** [comment]
>[error] (*:riffRaffUpload) com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain

I set up Travis and I might have used my own IAM user's AWS creds. Doesn't sound like something I would do, but anyway... You just need to create an IAM user for Travis and update the `AWS_*` environment variables in the Travis UI.

**Comment by fredex42** [comment]
@LATaylor-guardian do you know which AWS account we need credentials for here? Can one of us do it or does @cb372 need to set up the IAM user?

**Comment by LATaylor-guardian** [comment]
@fredex42 I think this resides in the deploy tools account which I don't have access too.

**Comment by fredex42** [comment]
@adamnfish could you sort out an IAM user so we can run the amigo tests again please?

**Comment by adamnfish** [comment]
I can, pop by my desk. Otherwise maybe better to get access via Janus so you can manage this yourselves.

**Comment by kenoir** [comment]
Closing as no need to use fork now.

**Pull request closed without merging**
