### PR TITLE
Teamcity agent as ansible roles

### PR DESCRIPTION
**Pull request by AWare**
This adds some ansible roles that should define a teamcity agent, hopefully we'll be able to bake and rotate these more frequently now.

### CODE REVIEW

**Comment by AWare** [comment]
This depends on https://github.com/guardian/amigo/pull/178, after which I'll add docker compose. 

With NVM, it requires the user to exist before installing, which I'm not sure how best to deal with.

**Comment by AWare** [comment]
This builds a build agent,  I'd like to chat about how we want to put this into production.

**Comment by franziskas** [comment]
@AWare can this be merged?

**Comment by AWare** [comment]
Not yet.

**Comment by AWare** [comment]
This has been doing a fair few teamcity builds this afternoon, so it's time to get this shipped.

**Comment by AWare** [comment]
This doesn't install zip on the instance.

**Pull request merged**
